# Etapa 1: Construcción
FROM golang:1.26.2-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o product-api ./cmd/api

# Etapa 2: Imagen final
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/product-api .
EXPOSE 8080
CMD ["./product-api"]